---
title: "Demonstration of nirvash"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Demonstration of nirvash}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

if (!require(nirvash)) { devtools::load_all() }
```

## Demo

v5.x系の[nehan.js](https://github.com/tategakibunko/nehan.js)の仕様によります。

```{r default_behav}
nirvash("
  わたくしといふ現象は
  仮定された有機交流電燈の
  ひとつの青い照明です
  （あらゆる透明な幽霊の複合体）
  風景やみんなといつしよに
  せはしくせはしく明滅しながら
  いかにもたしかにともりつづける
  因果交流電燈の
  ひとつの青い照明です
  （ひかりはたもち　その電燈は失はれ）
")
```

`context`に渡したベクトルは`split`に渡した文字でcollapseされます。

```{r collapsing}
nirvash(c("あれがデネブ", "アルタイル", "ベガ", "君は指差す　夏の大三角"))
```

行があぶれると段組されます。

```{r long_block}
nirvash("
心象のはひいろはがねから
あけびのつるはくもにからまり
のばらのやぶや腐植の湿地
いちめんのいちめんの諂曲模様
（正午の管楽よりもしげく
　琥珀のかけらがそそぐとき）
いかりのにがさまた青さ
四月の気層のひかりの底を
唾つばきし　はぎしりゆききする
おれはひとりの修羅なのだ
（風景はなみだにゆすれ）
砕ける雲の眼路をかぎり
　れいろうの天の海には
　　聖玻璃の風が行き交ひ
　　　ZYPRESSEN 春のいちれつ
　　　　くろぐろと光素エーテルを吸ひ
　　　　　その暗い脚並からは
　　　　　　天山の雪の稜さへひかるのに
　　　　　　（かげろふの波と白い偏光）
　　　　　　まことのことばはうしなはれ
　　　　　雲はちぎれてそらをとぶ
　　　　ああかがやきの四月の底を
　　　はぎしり燃えてゆききする
　　おれはひとりの修羅なのだ
　　（玉髄の雲がながれて
　　　どこで啼くその春の鳥）
　　日輪青くかげろへば
　　　　修羅は樹林に交響し
　　　　　陥りくらむ天の椀から
　　　　　　黒い木の群落が延び
　　　　　　　その枝はかなしくしげり
　　　　　　すべて二重の風景を
　　　　　喪神の森の梢から
　　　　ひらめいてとびたつからす
　　　　（気層いよいよすみわたり
　　　　　ひのきもしんと天に立つころ）
")
```

HTML文字列をそのままパースするのでタグや組み込みのクラスが使えます。文字列のサニタイズは必要に応じて自分でやってください。

```{r has_drop_cast}
nirvash("
<h2>雲の信号</h2>
<p class=\"drop-caps\">あゝいゝな　せいせいするな</p>
風が吹くし
農具はぴかぴか光つてゐるし
山はぼんやり
<ruby>岩頸<rt>がんけい</rt></ruby>だつて<ruby>岩鐘<rt>がんしよう</rt></ruby>だつて
みんな時間のないころのゆめをみてゐるのだ
　　そのとき雲の信号は
　　もう青白い春の
　　禁慾のそら高く<ruby>掲<rt>かか</rt></ruby>げられてゐた
山はぼんやり
きつと四本杉には
今夜は雁もおりてくる
")
```

nehan.js v5.x系までの独特の挙動として、1ケタの半角文字列は倒立します。半角数字は2ケタまで倒立します。また、4ケタまでは`tcy`というクラスを指定することで縦中横にできます。

```{r tcy}
nirvash("
A
A5
a
aa
5
50
500
5000
<span class=\"tcy\">5000</span>兆円ほしい
<span class=\"tcy\">A5</span>ランクの和牛
")
```

## SeesionInfo

```{r}
sessioninfo::session_info()
```
